<?php
namespace Api\Controller;
use Think\Controller;


class UserController extends PublicController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function __construct()
    {
        parent::__construct();


    }

    public function getPersonalInfo()
    {
        //$user_info = session("user_info");

        if (IS_POST) {

            $data = I("post.");
            var_dump($data);exit;
            $uid  = $data['uid'];


            if (!$uid) {
                errReturn();
            }

//            if ($uid != $user_info['uid']) {
//                errReturn('500', '非本人不可操作');
//            }

            $where['uid'] = $uid;
            $res = D("User", "Logic")->getUserInfo($where);

            if ($res['status'] != 200) {
                errReturn($res['status'], $res['info']);
            }

            succReturn($res['data']);
        }

        errReturn('500', '非法操作');

    }

    public function postPersonalInfo()
    {
        //$user_info = session("user_info");

        if (IS_POST) {

            $data = I("post.");
            $uid  = $data['uid'];

            if (!$uid) {
                errReturn();
            }

//            if ($uid != $user_info['uid']) {
//                errReturn('500', '非本人不可操作');
//            }

            $params['uid']       = $uid;
            $params['nick_name'] = $data['nick_name'];
            $params['birthday']  = $data['birthday'];
            $params['avatar']    = $data['avatar'];
            $res = D("User", "Logic")->uploadUserInfo($params);

            succReturn($res['data']);
        }

        errReturn('500', '非法操作');
    }

}